### PR TITLE
Improved README.md

### PR DESCRIPTION
**Pull request by biswadeep25**
### Context

Improved the readme.md file to make it easier for new contributors to understand erxes better.

### CODE REVIEW

**Comment by naurenbatjargal** [comment]
Hey @biswadeep25,

Thank you for your contribution. I'd really like to e-meet you in person just to get to know you better.  Any chance we could talk? it would be great if you can join our discord, so we could be able to meet there. 

Let me know.

**Comment by biswadeep25** [comment]
Ya sure, please send me the link

**Comment by biswadeep25** [comment]
Also, please merge my PR

**Comment by naurenbatjargal** [comment]
This is my [calendar](https://calendly.com/nauren/30min). Please book a call to chat.

**Pull request merged**
