### PR TITLE
rocketchat social media link added- #2163 

### PR DESCRIPTION
**Pull request by deepak-thakur**
[ISSUE](https://github.com/erxes/erxes/issues/ISSUE)

### Context

opening this PR request for Issue number #2163,
Issue link is : https://github.com/erxes/erxes/issues/2163

### CODE REVIEW

**Comment by deepak-thakur** [comment]
Hello when and who will verify my PR ?

**Comment by davidkartuzinski** [comment]
@deepak-thakur Hi! Sorry about the delay. I moved it over to the Develop branch. @Anu-Ujin will review the work you've done. If she is okay and doesn't require any changes, it will be merged to be released this Friday with the other changes.

**Comment by Anu-Ujin** [comment]
@deepak-thakur 
Thanks so much for your contribution. I have terrible news! This section you're fixing is about our Coming Soon plugins. But we're removing them... I am so sorry you spent time doing this. But for now, we are using roadmap.erxes.io to say what is coming and so we removed all coming soon stuff.  Again, so sorry but thank you so much. 

I really hope to see you continuing to contribute.

I am going to close this as it's not needed.  Thank you <3

**Comment by deepak-thakur** [comment]
Hello thank @Anu-Ujin and @davidkartuzinski for reviewing. It means my PR will not get merged ? 
If not then please can you remove those open issue's which are not needed to be fixed. Because i saw this issue 2163 in open issues. 😅

**Comment by davidkartuzinski** [comment]
@deepak-thakur - Thanks. Yes this means that we will **not** be merging your Pull Request. But you discovered a big issue. Some of our tickets and features from Productboard are automatically generating GitHub issues! This is why it is an open issue. We will go through all the issues and make sure they are really real issues to be handled.  

You have helped with a big issue!  Thank you so much.

**Comment by deepak-thakur** [comment]
I am glad that could help you.. 😃 @davidkartuzinski

**Pull request closed without merging**
