### PR TITLE
Added alt text to img files corresponding to contributors and backers

### PR DESCRIPTION
**Pull request by sandip2224**
# Context

Added required alt text to  tags with necessary modifications after initial review.

### CODE REVIEW

**Review by itsjustmithun — APPROVED** [review]

**Comment by saikhangombo** [comment]
@davidkartuzinski, Can you have a look at this please?

**Comment by saikhangombo** [comment]
Hi there, @sandip2224 Do not forget to star our erxes profile please.

**Comment by sandip2224** [comment]
@saikhangombo of course.😁

**Comment by davidkartuzinski** [comment]
@sandip2224 this issue was closed because your submission does not follow the guidelines.

**Pull request closed without merging**
