### PR TITLE
fix(docs): fix link to the docs start page in README

### LINKED ISSUE #2414: Link to docs in README.md is broken
**Describe the bug**
The link which should point to docs start page points to not existed page

Kind a related to https://github.com/erxes/erxes/issues/2352 update, which was made before

**To Reproduce**
1. Go to readme section
2. Click on erxes documentation link
3. You will be redirected to https://www.erxes.org/overview/getting-started/ and see this
Selection_109

**Expected behavior**
You should able to start work with docs

### LINKED ISSUE #2415: Link to installation guides in readme are broken
**Describe the bug**
Links to installation guides point to old urls, and now, doesn't work

**To Reproduce**
1. Go to Readme 
2. Click on, for example, Ubuntu guide
3. You will be redirected to https://www.erxes.org/

**Expected behavior**
You should see a relevant docs page

### PR DESCRIPTION
**Pull request by daniloff200**
Closes #2415 
Closes #2414

### Context
Update links in README.md

### CODE REVIEW

**Comment by daniloff200** [comment]
@davidkartuzinski hey :)

I've added here links to Debian10 and CentOS 8 guides, but, links are also broken.
However, in [docs/installation](https://github.com/erxes/erxes/tree/master/docs/docs/installation) we have such files, so, maybe, it also can be an issue.

**Comment by shinebayar-g** [comment]
> @davidkartuzinski hey :)
> 
> I've added here links to Debian10 and CentOS 8 guides, but, links are also broken.
> However, in [docs/installation](https://github.com/erxes/erxes/tree/master/docs/docs/installation) we have such files, so, maybe, it also can be an issue.

Yes. We should get rid of them as well.

**Comment by daniloff200** [comment]
@shinebayar-g  got your point
Gonna do that

**Comment by daniloff200** [comment]
@shinebayar-g  done

**Pull request merged**
