### PR TITLE
Removed .env.sample from docs and install scripts

### PR DESCRIPTION
**Pull request by sahil9001**
[ISSUE](https://github.com/erxes/erxes/issues/2034)

### Context

Removed ```cp .env.sample .env``` from docs at https://docs.erxes.io/developer/developer/ frontend setup.

### PR Checklist
- [x] Description is clearly stated under Context section
- [ ] Screenshots and the additional verifications are attached

### CODE REVIEW

**Comment by batamar** [comment]
Hi @sahil9001 . Please follow the contribution guide https://www.erxes.org/developer/contributing.
Please change the base from master to develop

**Comment by sahil9001** [comment]
> Hi @sahil9001 . Please follow the contribution guide https://www.erxes.org/developer/contributing.
> Please change the base from master to develop

Done @batamar

**Comment by batamar** [comment]
Hi @sahil9001. Thanks for the pr. I saw the changes. It is better to add lines like ```cd ui``` instead of removing the cp line. Because it is required and there is .env.sample file available in ui folder.

**Comment by sahil9001** [comment]
@batamar I've added required changes.

**Comment by batamar** [comment]
@sahil9001 thank you

**Pull request merged**
