### PR TITLE
Create es.json

### PR DESCRIPTION
**Pull request by DiFerGomAlv**
Added modified phrases to spanish (Different from the ones modified in the tribakzero's pull request)

### CODE REVIEW

**Comment by batamar** [comment]
@DiFerGomAlv Thanks for the pull request. Please split branch from develop and resend

**Comment by batamar** [comment]
@DiFerGomAlv Thanks for the pull request. Please split branch from develop and resend

**Comment by batamar** [comment]
@DiFerGomAlv Thanks for the pull request. Please split branch from develop and resend

**Comment by DiFerGomAlv** [comment]
> @DiFerGomAlv Thanks for the pull request. Please split branch from develop and resend

Hello, i am new to contributing to opensource. I don't understand what do you mean by "split branch from develop" i made my changes at a branch different to master (DiFerGomAlv:addSpanish),

what else do i have to do?

**Comment by batamar** [comment]
@DiFerGomAlv Hi. Here is our contribution guide. By split I mean create new branch from develop. It is common to create new branch from develop when you develop new feature (new language). Develop is our development branch. Our latest and unstable changes are in here. So if you send your pull request to this branch, I can compare your changes to our latest updates. And if your changes are simple and not much to review, I can merge your changes with develop branch right away

**Pull request closed without merging**
