### PR TITLE
Add some new words

### PR DESCRIPTION
**Pull request by aryangulati**
[ISSUE](https://github.com/erxes/erxes/issues/ISSUE)

### Context

Your context here.  Additionally, any screenshots.  Delete this line.

// Delete the below section once completed
### PR Checklist
- [x] Description is clearly stated under Context section
- [x] Screenshots and the additional verifications are attached

### CODE REVIEW

**Comment by aryangulati** [comment]
How can i get swags now??

**Comment by aryangulati** [comment]
I have made a PR and 3 issues

**Comment by mendorshikh** [comment]
@aryangulati Awesome! thank you. Please follow the steps here: https://erxes.io/hubspot-alternative-erxes-swag

**Comment by indraganzorig** [comment]
Hello @aryangulati, 
Thank you for contributing to erxes!
Please note that due to the COVID-19 outbreaks around the world, the shipment might be delayed. But we'll make sure you get them at some point.

**Comment by aryangulati** [comment]
Ok thank you so much but where I have to fill form or something like that
to give u all my details?
Or u will tell it later on when covid problem settle down?

**Comment by indraganzorig** [comment]
Are you having trouble finding the form?
We have a form like this on that page: 
Screenshot 2020-03-18 15 08 30

Which browser are you using?

**Comment by aryangulati** [comment]
Google Chrome

**Comment by aryangulati** [comment]
Ok thank you I got it

**Pull request merged**
