### PR TITLE
Solved issue #2360

### PR DESCRIPTION
**Pull request by aliya-rahmani**
[ISSUE](https://github.com/erxes/erxes/issues/ISSUE)
#2360 
### Context
I've fixed the broken link of graphs/contributors of README.md and CONTRIBUTING.md.

### CODE REVIEW

**Review by davidkartuzinski — APPROVED** [review]
This is good.  Thank you.

**Review by davidkartuzinski — APPROVED** [review]
Looks good still.

**Comment by afred-khan** [comment]
@davidkartuzinski Thanks, I'll take care of it next time. :)

**Comment by aliya-rahmani** [comment]
@davidkartuzinski Thanks, and I'll take care of it from next time. :)

**Pull request merged**
