### PR TITLE
Update README.md a grammatical error a pop-ups to  a pop-up.

### PR DESCRIPTION
**Pull request by sparkingdark**
Edited a pop-ups to a pop-up.

[ISSUE](https://github.com/erxes/erxes/issues/ISSUE)

### Context
I check the read-me and I found that there is a singular to plural error i found so I fixed that.
error is a pop-ups 
fix done a pop-up

// Delete the below section once completed
### PR Checklist
- [x] Description is clearly stated under Context section

### CODE REVIEW

**Review by davidkartuzinski — CHANGES_REQUESTED** [review]
There is grammatical error.  But making "pop-up" singular is not the correct solution. The rest of the sentence is a list of plural solution that we offer.  The correct solution is to keep "pop-ups" plural and to remove the word "a".  Please make this change a resubmit.

Are you sure this is the only thing you can correct in the Readme?

**Comment by sparkingdark** [comment]
Okay I do it and try to find some other grammatical errors if I can.

**Comment by sparkingdark** [comment]
Hello I rechecked and other no grammatical error found @davidkartuzinski.

**Review by davidkartuzinski — APPROVED** [review]
I will go ahead and approve this but simply removing the "a" and not the space is not really helpful, is it? 

In the future, please follow the contributing guidelines and make meaningful contributions to the project.  Otherwise it wastes valuable time for us trying to make erxes available as open source.

**Comment by sparkingdark** [comment]
Yeah I understand and in future try to do more meaningful contribution.

**Pull request merged**
