### PR TITLE
Corrected Grammatical Mistakes and added additional keywords

### PR DESCRIPTION
**Pull request by uravgkarthik**
[ISSUE](https://github.com/erxes/erxes/issues/ISSUE)

### Context

There was a grammatical mistake in src/pages/developer-partner.js and it has been successfully rectified.

### CODE REVIEW

**Comment by batamar** [comment]
Thanks @uravgkarthik . Please checkout changes. It has some unnecessary double quote changes

**Comment by uravgkarthik** [comment]
> Thanks @uravgkarthik . Please check the changes. It has some unnecessary double quote changes

Yes @batamar sorry for that. That's because of a VS Code Extension, it does it automatically

**Comment by batamar** [comment]
Please check the unnecessary quote updates

**Review by davidkartuzinski — COMMENTED** [review]
Changing CRM is unnecessary.

**Pull request closed without merging**
