### PR TITLE
Fix typo in codeblock in digitalocean.md

### PR DESCRIPTION
**Pull request by Atharva1723**
### Context
Fixed typo in codeblock in the documentation for digital ocean :
In the section about changing the NGINX configuration, there is a typo in the command:
It should be /etc/nginx/sites-available/default.conf instead of just default

// Delete the below section once completed
### PR Checklist
- [✔] Description is clearly stated under Context section

### CODE REVIEW

**Comment by Atharva1723** [comment]
Can this PR be reviewed ?

**Comment by Atharva1723** [comment]
@munkhsaikhan Can you please review this PR ?

**Comment by Atharva1723** [comment]
@munkhsaikhan Can you please review this PR ?

**Comment by vinyll** [comment]
@Atharva1723 The original docs seems right to me.

Checking on a regular Ubuntu:
```sh
ubuntu@ubuntu:~$ ls /etc/nginx/sites-available/default 
/etc/nginx/sites-available/default
```

And [the Digital Ocean doc](https://www.digitalocean.com/community/tutorials/nginx-essentials-installation-and-configuration-troubleshooting#server-configuration) also refers to _/etc/nginx/sites-available/default_

**Pull request closed without merging**
